### ISSUE TITLE
Command returned non-zero exit status 1

### ISSUE THREAD

**Issue by jiaxx** [AllenInstitute/ecephys_spike_sorting#33]
subprocess.check_call(command.split(' '))

error: subprocess.CalledProcessError: Command returned non-zero exit status 1

**Comment by harshk95** [comment]
Hi, while using the sglx_multi_run_pipeline.py I get the same issue.
I have installed Python 3.7.9. 
`
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ecephys\ecephys_spike_sorting\.venv\lib\site-packages\ecephys_spike_sorting\modules\catGT_helper\__main__.py", line 11, in <module>
    from ...common.utils import read_probe_json, get_repo_commit_date_and_hash, rms
  File "C:\ecephys\ecephys_spike_sorting\.venv\lib\site-packages\ecephys_spike_sorting\common\utils.py", line 9, in <module>
    from git import Repo
  File "C:\ecephys\ecephys_spike_sorting\.venv\lib\site-packages\git\__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

Traceback (most recent call last):
  File "sglx_multi_run_pipeline.py", line 342, in <module>
    logFullPath )
  File "C:\ecephys\ecephys_spike_sorting\ecephys_spike_sorting\scripts\helpers\run_one_probe.py", line 26, in runOne
    subprocess.check_call(command.split(' '))
  File "c:\users\user\appdata\local\programs\python\python37\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\ecephys\\ecephys_spike_sorting\\.venv\\Scripts\\python.exe', '-W', 'ignore', '-m', 'ecephys_spike_sorting.modules.catGT_helper', '--input_json', 'C:\\ecephys\\json_files\\test-input.json', '--output_json', 'C:\\ecephys\\json_files\\test_CatGT-output.json']' returned non-zero exit status 1.
`

Any pointers would be greatly appreciated.
Thanks!

**Comment by jsiegle** [comment]
Hi @harshk95, this portion of the code is used to track the exact version of the code that's being run, and is not necessary for any of the other functionality. I would recommend simply commenting out this line:

`from git import Repo`

and running the rest of the code as-is.

**Comment by harshk95** [comment]
Great thanks, I instead added the git.exe to path and it worked too. As another comment, I got the 'Command returned non-zero exit status 1' due to using `car_mode =  gbldmx` for CatGT but this has been retired, as far as I understand, in the current version and tshift is applied by default.

**Comment by jsiegle** [comment]
I'm not sure about that...perhaps @jenniferColonell can comment on that one?

**Comment by jenniferColonell** [comment]
Hi @harshk95 That's correct, the latest CatGT has retired gbldmx, but I haven't taken it out of the pipeline code yet. So, if you are running the latest pipeline and the newest CatGT, you'll get an error from CatGT rather than the pipeline code. I'll fix that in a later release. You're also correct that CatGT applies the tshift function with whatever filter you choose, unless you elect to skip it with the -no_tshift option.
