### ISSUE TITLE
batch_processing.py fails to execute any modules

### ISSUE THREAD

**Issue by ldclaar** [AllenInstitute/ecephys_spike_sorting#34]
When I run batch_processing.py, it returns non-zero exit status 1. I have attempted to run a few different modules (extract_from_npx and kilosort_helper) and it gives the same error. It seems that some of the paths are being set to None (in create_input_json.py) but something down the line doesn't like that.
![Field may not be null error](https://user-images.githubusercontent.com/45570217/58898169-d35c8c00-86ae-11e9-918e-235081754536.JPG)

**Comment by kate-prime** [comment]
Sorry for commenting on the extremely old tread, but how did you solve this? I'm having the same problem

**Comment by ldclaar** [comment]
It's hard for me to remember exactly why I was having this issue, but I can recall a few problems I have had in the past.

One issue I know I've had is I called the directory that I was passing to the "createInputJson()" function by the wrong name. If you look here (https://github.com/AllenInstitute/ecephys_spike_sorting/blob/master/ecephys_spike_sorting/scripts/create_input_json.py) you can see that you can specify the "npx_directory", "extracted_data_directory", and/or "kilosort_output_directory", and that will dictate some of the file locations it sets or doesn't set.

Another problem I have had is specifying the "probe_type" incorrectly (like calling it '1.0' instead of 'PXI'). But, in my opinion, that is less likely to cause the error above.
