### ISSUE TITLE
Potential synergy between this repository and SpikeInterface

### ISSUE THREAD

**Issue by colehurwitz** [AllenInstitute/ecephys_spike_sorting#40]
Hello!

I am a developer working on an open-source suite of tools ([SpikeInterface](https://github.com/SpikeInterface)) designed to standardize extracellular analysis and spike sorting. 

A lot of our work in the past year has gone into standardizing IO for both raw and sorted extracellular file formats, wrapping popular spike sorting algorithms in our framework, and developing comprehensive tools for ground truth analysis of different sorters (along with implementation of some preprocessing and postprocessing tools for spike sorting analysis). 

One part of our framework that still needs a lot of work is in the unsupervised metrics that can be used to evaluate the result of a spike sorter on datasets _without ground truth_. Recently, we discovered this repository and were impressed by the large suite of implemented metrics for this express purpose. We would love to get in touch and even discuss over email/skype about a possible integration of these metrics into SpikeInterface.

If you want to get in touch over email, my email is cole.hurwitz@ed.ac.uk.

Best,

Cole Hurwitz

**Comment by jsiegle** [comment]
Hi Cole, I just looked through the SpikeInterface code and docs, I'm very this project exists! We'd be happy to help integrate our quality metrics code into your repository. It looks like they'd be going into [this file](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/validation/qualitymetrics.py)?

In general, it would be helpful to get some feedback on what we've implemented so far, and to hopefully reach a consensus on exactly how these metrics should be computed. We've found that things like the method for sub-sampling spikes or the number of PCs included in the calculations can have a big impact on the results.

I'll send you an email to coordinate further!

**Comment by colehurwitz** [comment]
Hi Josh, thanks for getting back to me! I am glad that you are interested in our project! 

You are correct, we would be integrating your metrics into the quality metrics file. Part of the challenge will be making your metrics compatible with our RecordingExtractors and SortingExtractors which standardize data retrieval from any raw and sorted file formats, respectively. We can discuss that in future correspondence.

We would also be excited to discuss the metrics you implemented so far. Jeremy Magland is one of the core developers of our framework and he has done some [work](https://www.sciencedirect.com/science/article/pii/S0165027016300036) on validating spike sorting algorithms without ground-truth information.

It would be great if you CC these people as well in your upcoming email. They are the main team (along with me) behind building this framework:

Jeremy Magland: jmagland@flatironinstitute.org
Matthias Hennig: m.hennig@ed.ac.uk
Alessio Buccino: alessiob@ifi.uio.no
Samuel Garcia: samuel.garcia@cnrs.fr

**Comment by jsiegle** [comment]
These metrics have now been added to the [SpikeMetrics](https://github.com/SpikeInterface/spikemetrics) repository.
