### ISSUE TITLE
get_sessions method missing? 

### ISSUE THREAD

**Issue by nsteinme** [AllenInstitute/ecephys_spike_sorting#44]
Hey, I just tried to run the "quickstart" ipynb and it seems to succeed in importing the code and building the cache but I get an error right after that, see below. Any idea what I'm doing wrong? Thanks - 

![image](https://user-images.githubusercontent.com/7590975/67537354-d113c200-f68f-11e9-9838-7888a63cd184.png)

**Comment by nsteinme** [comment]
quickstart downloaded from this site (https://allensdk.readthedocs.io/en/latest/visual_coding_neuropixels.html), here's the direct link to what I downloaded:  https://allensdk.readthedocs.io/en/latest/_static/examples/nb/ecephys_quickstart.ipynb

**Comment by nsteinme** [comment]
also please let me know if this issue should be somewhere else, sorry

**Comment by nsteinme** [comment]
k nevermind found this which says the method was renamed, which works: https://github.com/AllenInstitute/AllenSDK/issues/1059

**Comment by jsiegle** [comment]
Glad you figured it out! The currently available version of that notebook is correct...you probably downloaded it when I sent you the link a while back, and the method was changed in the interim.
