### ISSUE TITLE
compiling median_subtraction

### ISSUE THREAD

**Issue by RobertoDF** [AllenInstitute/ecephys_spike_sorting#50]
Hi,

First of all, thanks for making all the analysis pipeline open access!

I am trying to compile the median_subtraction code but I am lost due to my ignorance of C++. 
I am following this [guide](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/build/walkthrough-compiling-a-native-cpp-program-on-the-command-line.md) but I end up with

`
Main.cpp
c:\users\akino s-900\downloads\ecephys_spike_sorting-master\ecephys_spike_sorting-master\ecephys_spike_sorting\modules\median_subtraction\spikebandmediansubtraction\source\../JuceLibraryCode/JuceHeader.h(18) : fatal error C1083: Cannot open include file: 'juce_audio_basics/juce_audio_basics.h': No such file or directory`

Can somebody point me to the right direction?

Thanks!

**Comment by jsiegle** [comment]
Hi Roberto,

The easiest solution is to just download the pre-compiled executable, available [here](https://github.com/AllenInstitute/ecephys_spike_sorting/files/4753545/SpikeBandMedianSubtraction.zip). 

If you want to compile it yourself (e.g., to make changes to the algorithm), you'll need to point Visual Studio to the Juce library files contained in another project, e.g. the [Open Ephys GUI](https://github.com/open-ephys/plugin-GUI/). If you are interested in going down this route, I can add some more documentation about exactly how to do this.

Josh

**Comment by RobertoDF** [comment]
Thanks Josh, I will pick the easy solution for now :)

**Comment by RobertoDF** [comment]
Hi Josh,
I managed to run the whole pipeline on windows  but now I need to do it on a linux machine and I get stuck at the same step. I tried to use the makefile but I get this:
`(base)roberto@alz1:~/Github/ecephys_spike_sorting/ecephys_spike_sorting/modules/median_subtraction/SpikeBandMedianSubtraction/Builds/LinuxMakefile$ make
Compiling Main.cpp
In file included from ../../Source/Main.cpp:14:0:
../../Source/../JuceLibraryCode/JuceHeader.h:18:10: fatal error: juce_audio_basics/juce_audio_basics.h: No such file or directory
 #include <juce_audio_basics/juce_audio_basics.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:85: recipe for target 'build/intermediate/Debug/Main_90ebc5c2.o' failed
`
I see that it's the same error as before, is there a shortcut that avoids the compiling step? (I am not interested in changing the algorithm)

**Comment by RobertoDF** [comment]
Hi Josh,
I managed to run the whole pipeline on windows but now I need to do it on a linux machine and I get stuck at the same step. I tried to use the makefile but I get this:
(base)roberto@alz1:~/Github/ecephys_spike_sorting/ecephys_spike_sorting/modules/median_subtraction/SpikeBandMedianSubtraction/Builds/LinuxMakefile$ make Compiling Main.cpp In file included from ../../Source/Main.cpp:14:0: ../../Source/../JuceLibraryCode/JuceHeader.h:18:10: fatal error: juce_audio_basics/juce_audio_basics.h: No such file or directory #include <juce_audio_basics/juce_audio_basics.h> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. Makefile:85: recipe for target 'build/intermediate/Debug/Main_90ebc5c2.o' failed
I see that it's the same error as before, is there a shortcut that avoids the compiling step? (I am not interested in changing the algorithm)

**Comment by jsiegle** [comment]
Hi @RobertoDF, a Linux version is available [here](https://github.com/AllenInstitute/ecephys_spike_sorting/files/4821847/SpikeBandMedianSubtraction.zip).

Let me know if that works for you!
