### ISSUE TITLE
l_ratio

### ISSUE THREAD

**Issue by bartulem** [AllenInstitute/ecephys_spike_sorting#52]
Hi guys,

On line 700 in the metrics.py script from the quality_metrics module, you have "mahalanobis_other" in the denominator of the l_ratio metric. I was wondering if this was a mistake and if it should rather be "mahalanobis_self"?

**Comment by jsiegle** [comment]
Good catch! Normalizing by the number of within-cluster spikes is correct. I will make sure this gets fixed here, as well as in the [spikemetrics](https://github.com/SpikeInterface/spikemetrics/blob/master/spikemetrics/metrics.py) repo.

**Comment by jsiegle** [comment]
Ok, fixed!

https://github.com/AllenInstitute/ecephys_spike_sorting/blob/d9d041e9e7d965d1e66fea0c213b4d0876be9e0e/ecephys_spike_sorting/modules/quality_metrics/metrics.py#L700-L701
