### ISSUE TITLE
build error on spike median subtraction module

### ISSUE THREAD

**Issue by Lozanoda** [AllenInstitute/ecephys_spike_sorting#67]
Hello, so i am trying to build compile the c++ for the median subtraction module and get this error attached. It seems like it cannot properly find the juce. cpp files. is there something i need to do with those before compiling the code? 
![image](https://user-images.githubusercontent.com/52248450/134737470-59051731-7aeb-46bf-9839-e9a1e9453491.png)

**Comment by jsiegle** [comment]
Did you manage to solve the problem?

**Comment by Lozanoda** [comment]
yes! I realized there was a solution in the closed issues section and downloaded the exe file which worked perfectly. Thank you!
