### ISSUE TITLE
"Files not available" on Quality Metrics module

### ISSUE THREAD

**Issue by JRicardo24** [AllenInstitute/ecephys_spike_sorting#72]
Hello, I just started to use your modules to process my Kilosort3 output a couple of days ago, and I am mainly interested in running both the Mean Waveforms and the Quality Metrics modules. After some initial drawbacks with instalation issues I was able to run the waveforms module, generating both the mean_waveforms.npy and waveform_metrics.csv files. When it comes to the Quality Metrics module, the following appears: 
![image](https://user-images.githubusercontent.com/72887221/173905435-882c316d-dbe8-4ecf-9a4c-f37abb223017.png)
Any idea of why is it not able to load the data? 
Maybe it's some variable I haven't defined yet, but I don´t quite know since the Mean Waveforms module did work. 
All the info related to the probe was not defined, only the num_channels=64 (neuronexus probe). 
On my create_input_json file I have only explicited the kilosort_output_directory, where I have the .dat file of the whole 2hour recording and the npy and tsv files that Kilosort3 outputed. That means, no extracted_data_directory or kilosort_output_tmp filepaths are defined. Don't know if the error is due to that, just trying to give the best detailed picture of the situation. 
Besides that, only defined the path to output_file (the directory where the input and output json files are stored).

Kind regards :)

**Comment by jsiegle** [comment]
Unlike KS2, KS3 doesn't generate the waveform principal components (PCs), which are needed for a subset of the quality metrics. To ignore the metrics that require PCs, just set the [`include_pc_metrics`](https://github.com/AllenInstitute/ecephys_spike_sorting/blob/7e567a6fc3fd2fc0eedef750b83b8b8a0d469544/ecephys_spike_sorting/scripts/create_input_json.py#L197) parameter to `False`. Hopefully once you do that the metrics will be computed successfully.

**Comment by JRicardo24** [comment]
@jsiegle It worked, perfect! 
I do want to get the metrics related to the PCs so I will analyse Kilosort's 2.5 output as well, being aware that the clustering algorithm is different. 

Thank you for the precise and fast reply :)
