### ISSUE TITLE
output json 

### ISSUE THREAD

**Issue by tianw6** [AllenInstitute/ecephys_spike_sorting#79]
I created an input json file using create_input_json.py. However, for each module to run, I need to create another output json. I didn't find an example of it. I'm wondering what I should put into this output json file? Thanks so much!

**Comment by jsiegle** [comment]
Hi Tian – each module will automatically generate an output JSON after it runs. This file contains the parameters that were used to run the module, as well as additional module-specific info.  You just have to specify the location where the output JSON will be saved.
