### ISSUE TITLE
Memory Mapping Implementation

### ISSUE THREAD

**Issue by zmingmin** [AllenInstitute/ecephys_spike_sorting#92]
When running the analysis with a 400GB dataset, the program experiences slowdowns, likely due to memory allocation issues. Is there a straightforward way to pre-allocate memory during parallel processing to improve performance? We use the default pipeline provided in the create_input_json.py

Thanks for any instructions!

**Comment by jsiegle** [comment]
Is there a particular step in the pipeline that's affected, or are they all running slow?

If you're looking to speed up processing times, I'd recommend migrating your spike sorting to use [SpikeInterface](https://spikeinterface.readthedocs.io/en/stable/), which is being actively developed and has many more features than `ecephys_spike_sorting`.

**Comment by zmingmin** [comment]
Thank you! The slowdown occurs during the final clustering step in Kilosort. I’ve come across some discussions about this in Kilosort. 
Thanks a lot for the suggestion to try SpikeInterface and I will definitely try.

**Comment by jsiegle** [comment]
Both `ecephys_spike_sorting` and SpikeInterface just provide wrappers around Kilosort -- so there's not much that can be done within these packages to speed up that step.

In any case, I think you'll find SpikeInterface to be a better option for building sorting pipelines, both in terms of flexibility and performance.
